name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up SSH key
        env:
          HF_SSH_KEY: ${{ secrets.HF_SSH_KEY }}
        run: |
          # Set up SSH key with preserved formatting
          mkdir -p ~/.ssh
          echo "$HF_SSH_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan huggingface.co >> ~/.ssh/known_hosts

      - name: Debug SSH setup
        run: |
          echo "Checking SSH key permissions and contents of ~/.ssh directory:"
          ls -la ~/.ssh
          echo "Contents of known_hosts:"
          cat ~/.ssh/known_hosts
          echo "Contents of id_ed25519 key:"
          cat ~/.ssh/id_ed25519 || echo "Could not read SSH key file"

      - name: Push to Hugging Face Spaces
        run: |
          git config --global user.email "shafquat.shayan@gmail.com"
          git config --global user.name "shayanshafquat"
          git remote add hf ssh://git@huggingface.co/spaces/neuralnavigators/RAG
          git push hf main --force