name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "shafquat.shayan@gmail.com"
          git config --global user.name "shayanshafquat"
          
          # Set up credential helper to use HF_TOKEN for Hugging Face URL
          git config --global credential.helper store
          echo "https://huggingface.co/spaces/neuralnavigators/RAG" > ~/.git-credentials
          echo "https://${HF_TOKEN}:@huggingface.co/spaces/neuralnavigators/RAG" > ~/.git-credentials
          
          # Add the Hugging Face remote and push
          git remote add hf https://huggingface.co/spaces/neuralnavigators/RAG
          git push hf main --force